<?php

class CRM_Medatahealthchecker_DataChecker_ErrorCodes {

  CONST DD_PAYMENT_METHOD_WITH_NO_PAYMENT_PLAN = 100;

  CONST MISSING_FINANCIAL_TRANSACTION_RECORDS_ON_CONTRIBUTION = 200;

  CONST MISSING_LINE_ITEMS_ON_CONTRIBUTION = 300;

  CONST MISSING_FINANCIAL_ITEM_RECORDS_ON_LINE_ITEM = 400;

  CONST CONTRIBUTIONS_WITH_MISMATCHED_LINE_ITEMS_AMOUNT = 500;

  CONST CONTRIBUTIONS_WITH_MISMATCHED_LINE_ITEMS_TAX = 600;

  CONST OFFLINE_PAYMENT_PLANS_WITH_NO_MEMBERSHIPS = 700;

  CONST OFFLINE_PAYMENT_PLANS_WITH_AUTORENEW_FLAG_FALSE = 800;

  CONST OFFLINE_PAYMENT_PLANS_WITH_NO_SUBSCRIPTION_LINE_ITEMS = 900;

  CONST DIRECT_DEBIT_PAYMENT_PLANS_WITH_NO_MANDATES = 1000;

  CONST DIRECT_DEBIT_CONTRIBUTIONS_WITH_NO_MANDATES = 1100;
}
